services:
  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - '6789:6789'
  
  web:
    build: .
    container_name: web
    ports:
      - "5000:5000"
    volumnes:
      - .:/server
    depends_on:
      - redis